### ISSUE TITLE
Not all notes captured.

### ISSUE THREAD

**Issue by thesamim** [mbirk/dynalist_to_markdown#2]
In the following structure:
- _test

    - Line 1

      Note 1

        - Line 2

          Note 2

            - Line 3

              Note 3

                - Line 4

                  Note 4

                  

Only Note 4 is captured.

I don't know python, but changed the code as follows:

`

def document_to_markdown(self, path, node_by_id, config, out):
        for context in self.traverse_nodes(node_by_id, 'root'):
            node    = context[-1]
            content = node['content']

            if config.obsidian_internal_links:
                content = self.replace_markdown_links(content)

            #Header
            if len(context) <= config.heading_depth:
                if len(context) > 1:
                    print(file=out)
 
                depth   = len(context)
                heading = '#' * depth
                print(f'{heading} {content}', file=out)
                if config.include_notes:
                    note = node.get('note', '')
                    if note != '':
                        indent = len(context) - config.heading_depth - 1
                        indent = '\t' * indent
                        print(f'> [!note]\n {note}', file=out)
            #Text    
            else:
                indent = len(context) - config.heading_depth - 1
                indent = '\t' * indent
                print(f'{indent}- {content}', file=out)
                if config.include_notes:
                    note = node.get('note', '')
                    if note != '':
                        indent = len(context) - config.heading_depth - 1
                        indent = '\t' * indent
                        print(f'> [!note]\n {note}', file=out)

`

The result is that all notes are captured in a "Note" call out.

This is not an elegant solution, but works for my use case.

Sharing in case it helps.

**Comment by mbirk** [comment]
Thanks, @thesamim ... was indeed an oversight due to how my Dynalist repo was setup (with nearly all notes on leaf nodes).  Fixed.

**Comment by thesamim** [comment]
> Thanks, @thesamim ... was indeed an oversight due to how my Dynalist repo was setup (with nearly all notes on leaf nodes). Fixed.

Thanks @mbirk !
